### ISSUE TITLE
Update for mpich 4

### ISSUE THREAD

**Issue by jchodera** [choderalab/cluster-utils#12]
Running with mpich 4 gives this error:
```bash
$ build_mpirun_configfile --configfilepath configfile_apo --hostfilepath hostfile_apo "python run_multistate_sampler.py"
Detected MPICH version 4! 
Your host and configfiles creation will still be attempted, but you may have problems as build_mpirun_configfile only builds MPICH3 compatible files.
Traceback (most recent call last):
  File "/lila/home/chodera/miniconda/envs/openmmtools/bin/build_mpirun_configfile", line 10, in <module>
    sys.exit(main())
  File "/lila/home/chodera/miniconda/envs/openmmtools/lib/python3.10/site-packages/clusterutils/build_mpirun_configfile.py", line 249, in main
    manager.write_configfile(exec_args, configfile_output_filepath=args.configfilepath,
  File "/lila/home/chodera/miniconda/envs/openmmtools/lib/python3.10/site-packages/clusterutils/build_mpirun_configfile.py", line 96, in write_configfile
    for host, cvd in self.extract_host_cuda_visible_devs():
  File "/lila/home/chodera/miniconda/envs/openmmtools/lib/python3.10/site-packages/clusterutils/build_mpirun_configfile.py", line 194, in extract_host_cuda_visible_devs
    cvd_list.append([host, looped_cvd[n]])
IndexError: list index out of range
```

**Comment by jchodera** [comment]
This issue is likely unrelated to mpich4---it appears that `CUDA_VISIBLE_DEVICES` is not being properly set.
