### ISSUE TITLE
Errors on lilac

### ISSUE THREAD

**Issue by jchodera** [choderalab/cluster-utils#8]
I get this on `lilac`:
```
bash-4.2$ build_mpirun_configfile "python openmm_setup.py"
Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/build_mpirun_configfile", line 11, in <module>
    load_entry_point('clusterutils==0.2.0', 'console_scripts', 'build_mpirun_configfile')()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/clusterutils/build_mpirun_configfile.py", line 209, in main
    hostfile_output_filepath=args.hostfilepath)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/clusterutils/build_mpirun_configfile.py", line 96, in write_configfile
    for host, cvd in self.extract_host_cuda_visible_devs():
  File "/home/chodera/miniconda/lib/python3.5/site-packages/clusterutils/build_mpirun_configfile.py", line 192, in extract_host_cuda_visible_devs
    looped_cvd = [int(i) for i in self.cuda_visible_devices[host].split(',')]
  File "/home/chodera/miniconda/lib/python3.5/site-packages/clusterutils/build_mpirun_configfile.py", line 192, in <listcomp>
    looped_cvd = [int(i) for i in self.cuda_visible_devices[host].split(',')]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by jchodera** [comment]
Note that my `$CUDA_VISIBLE_DEVICES` is empty:
```
bash-4.2$ echo $CUDA_VISIBLE_DEVICES

bash-4.2$ 
```

**Comment by jchodera** [comment]
I presume this needs to be used with some magical incantation during the `bsub`?

**Comment by jchodera** [comment]
For reference, I was submitting with `bsub -app wholenode_GTX1080 -n 72 -Is bash` for testing purposes, and then ran `build_mpirun_configfile "python openmm_setup.py"`.

**Comment by Lnaden** [comment]
I dont think this is a problem anymore, I'm going to close the issue and we can reopen it if its a problem.
